### ISSUE TITLE
Resize cropper canvas

### ISSUE THREAD

**Issue by Lizonchik** [Mawi137/ngx-image-cropper#20]
I set the height to `<image-cropper>`. And when I upload the image with portrait orientation locating of cropper area is not in the appropriate place. 

P. S.: cropper is initing in the dialog (modal) window

![screenshot from 2018-03-01 18-34-21](https://user-images.githubusercontent.com/13273764/36856662-376f9ace-1d7f-11e8-834e-d79231afda85.png)

**Comment by Mawi137** [comment]
You should be able to place a max-height on the image cropper.
Does it have 100% width now? The image cropper should adjust its size to the chosen image.

**Comment by Lizonchik** [comment]
I have tried to set a max-height and a height, but the result is the same
Now the parent container has 100% width, image is centered, but `.cropper`has property `left: 0`.
I have tried to change width after image loaded, but it doesn't work :(
![screenshot from 2018-03-05 10-54-00](https://user-images.githubusercontent.com/13273764/36965852-8fba1d80-2063-11e8-99a9-1e76508e67cb.png)

**Comment by Mawi137** [comment]
I wouldn't add any styling to the image cropper itself, besides  optionally a max-height and max-width. I'd wrap the image-cropper in a div and apply the styles to that in order to center the image.
`display: flex`
`justify-content: center;`
`width: 100%`
That should do the trick.

**Comment by Lizonchik** [comment]
I tried to use these styles, and now I have the next problem
![screenshot from 2018-03-07 14-01-49](https://user-images.githubusercontent.com/13273764/37091244-1debc57e-2210-11e8-8dc2-5b74b5d59b77.png)

**Comment by Mawi137** [comment]
Could you recreate it in a StackBlitz? (stackblitz.com)
Hard to tell what's wrong like this.

**Comment by karloscode** [comment]
Hi, i have the similar issues when try to center the cropper inside div.
![captura](https://user-images.githubusercontent.com/20030179/37275188-cfeb324c-25de-11e8-98f8-7beb882c0728.PNG)

**Comment by Lizonchik** [comment]
@Mawi137 https://stackblitz.com/edit/angular-q91dxt

**Comment by Mawi137** [comment]
Hmm okay, I'll need to get the bounds some other way to fix this.
For now, adding this style should make it work correctly again:
```
image-cropper {
  text-align: left;
}
```
And also remove the height from the cropper itself, you can give it a `max-height`.

**Comment by Mawi137** [comment]
Should be fixed in version 0.1.27!

**Comment by Lizonchik** [comment]
I've upgraded the version, but the problem is still there. Can you look at my code, maybe I'm doing something wrong?
https://stackblitz.com/edit/angular-q91dxt

**Comment by Mawi137** [comment]
Nope, my mistake ;) Fixed it and tested it in your StackBlitz!

**Comment by dmitriytretyakov** [comment]
I have two projects with this module, and one of them is broken. I compare it and detect that in one of projects in .cropper div no margin-left property. It need to center crop and depends on image width. But i don't the reason why it not set.
