### ISSUE TITLE
View not updated when use in Ionic 3

### ISSUE THREAD

**Issue by nkCreation** [Mawi137/ngx-image-cropper#38]
Hello ! First of all, a really big thank you for this plugin. It's very fast and it's what I needed.

But - there's a but - I've seen an issue when building my ionic app : the view is not updated when I move or resize the picture (only the view).

I've already seen that before so I knew how it can be corrected. I forked the repo and add a reference to 

`ChangeDetectorRef`

in the file.

I will make a PR !

**Comment by Mawi137** [comment]
Hi, thanks for the PR! Glad to hear you made it work in Ionic ;) I changed the code a little and added the ChangeDetectionStrategy and the `markForCheck` call where needed. Version 0.2.5 should fix it.

**Comment by anil1712** [comment]
@Mawi137 I tried it with `0.2.5` but I am getting the same issue.
Can you please reopen it again.

**Comment by nkCreation** [comment]
Hi ! I just test on my phone and the problem is still here (but it's better !)
Before, the view wasn't updated. Now the view is updated when you remove your finger (during the crop and the resize, the view is not updated).

**Comment by nkCreation** [comment]
Hi. Any news about this ?

**Comment by nkCreation** [comment]
Hello. FYI I'm still using the fork I've made in my ionic 3 app.

**Comment by nkCreation** [comment]
Hello. Updating to the latest : 1.2.1 but still have the bug. Did you have the time to look at it ?

**Comment by Mawi137** [comment]
Hi @nkCreation, I tried it with Ionic in a browser, but it appears that didn't have the same effect. I just made some changes and tested it on my phone in an Ionic app and it works! For some reason it does need the `ChangeDetectorRef` to be called in the view that handles the output after an image is cropped, but then it works :)

**Comment by nkCreation** [comment]
You rocks !
I will test on my app today :)
